apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flask-api.fullname" . }}-config
  labels:
    {{- include "flask-api.labels" . | nindent 4 }}
data:
  # Application configuration
  APP_DEBUG: "{{ .Values.app.debug | default "false" }}"
  APP_LOG_LEVEL: "{{ .Values.app.loglevel | default "info" }}"

  # Database config not including credentials
  DB_HOST: "{{ .Release.Name }}-mysql"
  DB_PORT: "3306"
  DB_NAME: "{{ .Values.mysql.auth.database }}"

  # Others
  {{- if .Values.app.config }}
  {{- range $key, $val := .Values.app.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
