{{- if and .Values.rbac.create .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "flask-api.fullname" . }}-rolebinding
  labels:
    {{- include "flask-api.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "flask-api.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "flask-api.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
