---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jwt-secrets
  namespace: flask-api
spec:
  encryptedData:
    jwt-refresh-secret-key: AgAyjC4sgM/BMgK4fK+IPFK0palCiC6ID4Jq2PJIIwwdywT04zqqTKwYgw3E5bBEiK8zfnqjbP3Z9RQgpiciQ2MP4HuRxTN1znzos46akCiOBLcrV0jKbYshh+zGyo/e87sbiVHsXCKxUQVJKbofbq7vBX1s/SmZT5pIsryWyyVs3afNoU5GWfFOFf0Kc30FS5nE4kxF0fe1fGslvZPLQLdvN3DY47Fa9rlSsIOvULETJgyWvYI0lTnBp9YJ/KUngSA9BNEJ3PVm7teeWbdNFxuoz6nGr2Am6oxSKN2Yc9QOmN1mipYTAN6GCaEiqWhWAWuiDTNqPSTJHaII6FBVJu/OVZ8Kr8jfPxmPrqNapLSMhENmFzS+lnJBu3A/2xu9VwA2HjWItLIZizFG0JH7kbrEsK2kvN3lo2gADMw5PvWZBc2TqCeQPEIlVJkMrWDEgGIA0JuT+m4xHqC6mCO4HyoXT4B84R10LtbAflvtZm/UJOF12drPplVpQ/h3Is6AxPqbmigEZploNJllYFzNzdPiJl0sgfSnNfqCStPLVohJJKU8liMU06SiKVKfrQ3RoWZ7eduqXagLv0XMjYfYOQgrWGZvH0C7GucFrJ93J9C/5l67IxlTo32axFfrd5qsEyRw4ZLARYaWEHIs1sT0KXYT+8hlshtdOLTz2Gc02Z7KXBZrcllZxSLYO3JpAL+6VKnF6UNeSzgKt4aoiKJ41jc/b1tZY/NUmP74feqNXrWFowEOjqBhKTcFm9KWnQ==
    jwt-secret-key: AgA+F6kVEEIpVdu2ck+4AFVIBu6wIe7givFFLzolK15BkCwhCaA16CF8LCnKu5IOcpqWlboApCCGlYYueaU21QXR5Bqtz2rFwGikhYbFeytNABYKoNQf2ufUagMTHV+fI3CWT6Qms9NV693OpUeDDMWS5xIIgWZT001bB4hmH0gQsfwP1vl8b0uepg9cED8yiLvNR1A092xtVrx6m/CD7KOQqEQHwnTMHxau0exD50a+1CsSltaf50Gd3iqVp4j5XAOAY92bjFabSTlzH0VBQ0lo+Kjl/CJVHiTLSaWWSTgeKmrF3DELan8Dzk1VCSE8yQgdl9aOCB877m25vBEtTwt4Pj6ltdjAyCJZQY66z88GuaGvY/g1wKK74OdNepPnz0Ems9VSzsWM0gKA2cxiPMjJE7fqokC+E4pzIdaM/stceWKqcT2rOCG7TLmla7hKrA0kRn0YI6teSudxwvivrJZNhsMHjfzBCUCxSz3N+gY2cJWGIdoPBbin/zYSq9Y3aFrkbiH9lsncowXdoVejaXZWYl8P0RwHQXfUrs1BNAol+D3bIJiswl/PwkdDmMDcnDHH28DSDg6sIw2oFtU0CF/hNmGat1DtKrPhtCAygzK+wCJczVg2mCPFayR3kvnG4EK+Tl26MHxArFXGsCaCWGxtMvg0SbcYFrcMVLPIdnVvfbFWCqrCvZxLCbYBjzGMMgTa2k9R0gNoLMxeVYyJK+PMPTIk7T/moTiOeXNeXjm98Wwo7zFM7j1fBiu1Vg==
  template:
    metadata:
      creationTimestamp: null
      name: jwt-secrets
      namespace: flask-api
    type: Opaque
