{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flask-api.fullname" . }}
  namespace: {{ .Values.monitoring.grafana.dashboards.namespace | default .Release.Namespace }}
  labels:
    {{- include "flask-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "flask-api.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
  namespaceSelector:
    matchNames:
      - {{ .Values.monitoring.serviceMonitor.namespace | default .Release.Namespace }}
{{- end }}
