name: Flask API CI Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run linting
        run: |
          pip install flake8 black
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          black --check .
          
      - name: Run tests
        run: |
          pytest tests/
          
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/flask-api
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=sha,format=short
            
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
          
      - name: Lint Helm chart
        run: |
          helm lint ./flask-api-chart
          
  k8s-manifests:
    needs: [build, helm-lint]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - uses: actions/checkout@v3
      
      - name: Update Helm chart values
        run: |
          # Update the image tag in values.yaml to match the Git SHA
          yq -i '.image.tag = "${{ github.sha }}"' ./flask-api-chart/values.yaml
          # Update the image repository to point to the container registry
          yq -i '.image.repository = "ghcr.io/${{ github.repository }}/flask-api"' ./flask-api-chart/values.yaml
          # Update pull policy to ensure latest image is used
          yq -i '.image.pullPolicy = "Always"' ./flask-api-chart/values.yaml
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update container image to ${{ github.sha }}'
          add: './flask-api-chart/values.yaml'
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
